FROM registry.biz.com/openjdk:8-jdk-slim as builder

# 根据 wrapper 下载 gradle
WORKDIR /home/gradle/src
COPY gradlew /home/gradle/src/gradlew
COPY gradle/wrapper /home/gradle/src/gradle/wrapper
RUN ./gradlew --version

COPY . /home/gradle/src

RUN echo "======================================== test" \
  && ./gradlew clean test

RUN echo "======================================== build" \
  && ./gradlew :ufc:ufc-api:build -x test

RUN echo "======================================== build result" \
  && ls ufc/ufc-api/build/libs/ufc-api-*.jar

FROM registry.biz.com/openjdk:8-jre-slim
ENV TZ Asia/Shanghai
EXPOSE 8080
COPY scripts/docker/agent/agent.tar.gz /app/agent.tar.gz
RUN tar -zxvf /app/agent.tar.gz -C /app
COPY --from=builder /home/gradle/src/ufc/ufc-api/build/libs/ufc-api-*.jar /app/ufc-api.jar
WORKDIR /app
CMD java -jar ufc-api.jar
